# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/overrides.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(395, 761)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pastTenseBox = QtWidgets.QGroupBox(Dialog)
        self.pastTenseBox.setGeometry(QtCore.QRect(30, 270, 221, 71))
        self.pastTenseBox.setObjectName("pastTenseBox")
        self.checkBox = QtWidgets.QCheckBox(self.pastTenseBox)
        self.checkBox.setGeometry(QtCore.QRect(20, 30, 85, 18))
        self.checkBox.setObjectName("checkBox")
        self.futureAndConditionalBox = QtWidgets.QGroupBox(Dialog)
        self.futureAndConditionalBox.setGeometry(QtCore.QRect(30, 350, 221, 80))
        self.futureAndConditionalBox.setObjectName("futureAndConditionalBox")
        self.futureAndCondEnding = QtWidgets.QComboBox(self.futureAndConditionalBox)
        self.futureAndCondEnding.setGeometry(QtCore.QRect(100, 20, 104, 26))
        self.futureAndCondEnding.setObjectName("futureAndCondEnding")
        self.futureAndCondEnding.addItem("")
        self.futureAndCondEnding.addItem("")
        self.futureAndCondEnding.addItem("")
        self.label_2 = QtWidgets.QLabel(self.futureAndConditionalBox)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 56, 13))
        self.label_2.setObjectName("label_2")
        self.presentTenseBox = QtWidgets.QGroupBox(Dialog)
        self.presentTenseBox.setGeometry(QtCore.QRect(30, 130, 219, 131))
        self.presentTenseBox.setObjectName("presentTenseBox")
        self.go_verb = QtWidgets.QCheckBox(self.presentTenseBox)
        self.go_verb.setGeometry(QtCore.QRect(20, 30, 85, 18))
        self.go_verb.setObjectName("go_verb")
        self.oy_verb = QtWidgets.QCheckBox(self.presentTenseBox)
        self.oy_verb.setGeometry(QtCore.QRect(90, 30, 85, 18))
        self.oy_verb.setObjectName("oy_verb")
        self.label = QtWidgets.QLabel(self.presentTenseBox)
        self.label.setGeometry(QtCore.QRect(10, 60, 141, 21))
        self.label.setObjectName("label")
        self.radicalStemChanging = QtWidgets.QComboBox(self.presentTenseBox)
        self.radicalStemChanging.setGeometry(QtCore.QRect(100, 80, 104, 26))
        self.radicalStemChanging.setObjectName("radicalStemChanging")
        self.radicalStemChanging.addItem("")
        self.radicalStemChanging.addItem("")
        self.radicalStemChanging.addItem("")
        self.radicalStemChanging.addItem("")
        self.radicalStemChanging.addItem("")
        self.gerundBox = QtWidgets.QGroupBox(Dialog)
        self.gerundBox.setGeometry(QtCore.QRect(30, 430, 221, 80))
        self.gerundBox.setObjectName("gerundBox")
        self.pastParticiple = QtWidgets.QGroupBox(Dialog)
        self.pastParticiple.setGeometry(QtCore.QRect(30, 520, 221, 80))
        self.pastParticiple.setObjectName("pastParticiple")
        self.adjectiveBox = QtWidgets.QGroupBox(Dialog)
        self.adjectiveBox.setGeometry(QtCore.QRect(30, 610, 221, 80))
        self.adjectiveBox.setObjectName("adjectiveBox")
        self.adjUsePastParticiple = QtWidgets.QCheckBox(self.adjectiveBox)
        self.adjUsePastParticiple.setGeometry(QtCore.QRect(10, 30, 171, 18))
        self.adjUsePastParticiple.setChecked(True)
        self.adjUsePastParticiple.setObjectName("adjUsePastParticiple")
        self.endingBasedBox = QtWidgets.QGroupBox(Dialog)
        self.endingBasedBox.setGeometry(QtCore.QRect(30, 10, 221, 101))
        self.endingBasedBox.setObjectName("endingBasedBox")
        self.standardEndingOverride = QtWidgets.QCheckBox(self.endingBasedBox)
        self.standardEndingOverride.setGeometry(QtCore.QRect(30, 30, 151, 18))
        self.standardEndingOverride.setObjectName("standardEndingOverride")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_("Overrides for ____"))
        Dialog.setAccessibleName(_("Overrides"))
        self.pastTenseBox.setTitle(_("Past Tense"))
        self.checkBox.setText(_("E and O"))
        self.futureAndConditionalBox.setTitle(_("Future and Conditional"))
        self.futureAndCondEnding.setItemText(0, _("Infinitive"))
        self.futureAndCondEnding.setItemText(1, _("er -> dr"))
        self.futureAndCondEnding.setItemText(2, _("_r -> r"))
        self.label_2.setText(_("Ending"))
        self.presentTenseBox.setTitle(_("Present Tense"))
        self.go_verb.setToolTip(_("Go Verbs ( tengo, caigo )"))
        self.go_verb.setText(_("-g verb"))
        self.oy_verb.setToolTip(_("voy, soy"))
        self.oy_verb.setText(_("-oy verb"))
        self.label.setText(_("Radical Stem Changers"))
        self.radicalStemChanging.setItemText(0, _("None"))
        self.radicalStemChanging.setItemText(1, _("e:ie"))
        self.radicalStemChanging.setItemText(2, _("e:i"))
        self.radicalStemChanging.setItemText(3, _("o:ue"))
        self.radicalStemChanging.setItemText(4, _("u:ue"))
        self.gerundBox.setTitle(_("Gerund (-ing)"))
        self.pastParticiple.setTitle(_("Past Participle"))
        self.adjectiveBox.setTitle(_("Adjective"))
        self.adjUsePastParticiple.setText(_("Use Past Participle Form"))
        self.endingBasedBox.setTitle(_("Ending based"))
        self.standardEndingOverride.setText(_("replace with ending"))

