#!/bin/bash
#
# generate python files based on the designer ui files. pyuic4 and pyrcc4
# should be on the path.
#

if [ ! -d "designer" ]
then
    echo "Please run this from the project root"
    exit
fi
addon_dir=conjugate_spanish/ui
mkdir -p $addon_dir/forms

init=$addon_dir/forms/__init__.py
temp=$addon_dir/forms/scratch
rm -f $init $temp
echo "# This file auto-generated by build_ui.sh. Don't edit." > $init
echo "__all__ = [" >> $init

echo "Generating forms.."
for i in designer/*.ui
do
    base=$(basename $i .ui)
    py="$addon_dir/forms/${base}.py"
    echo "	\"$base\"," >> $init
    echo "import $base" >> $temp
    if [ $i -nt $py ]; then
        echo " * "$py
        pyuic5 $i -o $py
        # munge the output to use gettext
        perl -pi.bak -e 's/(QtGui\.QApplication\.)?_?translate\(".*?", /_(/; s/, None.*/))/' $py
        rm $py.bak
    fi
done
echo "]" >> $init
cat $temp >> $init
rm $temp

#echo "Building resources.."
#pyrcc5 designer/icons.qrc -o $addon_dir/forms/icons_rc.py
